[project]
name = "pharma_adherence"
version = "0.1.0"
description = "Analysis of pharma patient medication adherence"
authors = [
    {name = "AJ", email = "aj@gmail.com}
]
readme = "README.md"
license = {text = "MIT"}
requires_python = ">=3.10"

dependencies = [
    "mathplotlib",
    "pandas",
    "numpy",
    "scikit-learn"
]

[project.optional-depndencies]
dev = [
    "pytest",
    "setuptools",
    "wheels"
]

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.package-dir]
"" = "src"

[tool.setuptools.packages.find]
where = ["src"]
include = ["pharma_adherence*"]